### ISSUE TITLE
Relative links to images

### ISSUE THREAD

**Issue by aschempp** [contao/docs-archive#128]
@leofeyer GitHub now supports relative links to the images. However, what if we deploy to contao.org? I assume we are currently linking to GitHub?

**Comment by leofeyer** [comment]
No, we are not. They stated some time ago that `raw.github.com` is not a CDN and asked people not to link to the sub domain. You can change the links as you like (as long as the images are still visible on GitHub).

**Comment by aschempp** [comment]
perfect :-)

**Comment by aschempp** [comment]
I have updated all manuals in all versions to use relative links. Please make sure it still works on contao.org!

@lionel-m you might want to adapt that to the french version of the manual.

**Comment by lionel-m** [comment]
This is modified. Thx

**Comment by leofeyer** [comment]
I have modified the importer on contao.org accordingly.
