### ISSUE TITLE
Falsche Darstellung im Kochbuch

### ISSUE THREAD

**Issue by no-one** [contao/docs-archive#135]
Bei dem Absatz, der mit `Wenn man einen zweigeteilten Inserttag verwendet` beginnt, ist die Formatierung nicht korrekt (der Absatz wird im Code angezeigt).
Vergleiche hierzu https://github.com/contao/docs/blob/3.2/cookbook/de/Eigene-Inserttags.md und https://contao.org/de/cookbook/3.2/eigene-inserttags.html

**Comment by xchs** [comment]
Ich hab dazu bereits einen Pull Request gemacht (siehe #134)
