### ISSUE TITLE
TL_HOOK validateFormField 2.11 (3.x?)

### ISSUE THREAD

**Issue by toteph42** [contao/docs-archive#14]
Bei dem Hook wird der callback mit DREI Parameter aufgerufen: ($objWidget, $formId, $arrData). Ref: modules/frontend/Form.php:177. In der Doku sind nur zwei.

**Comment by aschempp** [comment]
Danke für den Hinweis. Die neue Hook-Doku entsteht separate, dein Kommentar ist bereits vorhanden (siehe https://github.com/contao/docs/blob/3.0/hooks/hooks/validateFormField.md)
