### ISSUE TITLE
imageSize

### ISSUE THREAD

**Issue by magicsepp** [contao/docs-archive#141]
In der LIste fehlt 'imageSize' als inputType oder hat das einen besonderen Hintergrund?
https://github.com/contao/docs/blob/3.2/manual/de/06-Data-Container-Arrays.md

**Comment by aschempp** [comment]
Da fehlt noch mehr, z.B. `timePeriod`. Magst du die Doku ergänzen und einen Pull Request stellen?

**Comment by magicsepp** [comment]
erstellt...

**Comment by aschempp** [comment]
Alles weitere in #142
