### ISSUE TITLE
header_callback nicht in Referenz

### ISSUE THREAD

**Issue by iCodr8** [contao/docs-archive#146]
Der header_callback für Sortierungsmodus 4 ist in der Referenz nicht beschrieben.
DCA -> table -> list -> sorting -> header_callback

**Comment by aschempp** [comment]
Könntest du das beschreiben und einen Pull-Request stellen?

**Comment by aschempp** [comment]
Meanwhile added in https://docs.contao.org/books/api/dca/callbacks.html#listing-callbacks
