### ISSUE TITLE
Benutzer Zugriff auf Artikeleinstellungen

### ISSUE THREAD

**Issue by Luminanz** [contao/docs-archive#147]
Hallo 
Aus meiner Sicht ist folgendes Verhalten nicht ganz konsequent:

Ein Benutzer, der keinerlei Zugriff auf die Artikeleinstellungen (Felder von tl_article) hat erhält in der Hauptansicht der Artikel das entsprechende Icon ("Einstellungen des Artikels ID xy bearbeiten") ausgegraut dargestellt. Soweit so gut.
Jedoch wird in der Ansicht eines einzelnen Artikels das Symbol wieder als aktiv dargestellt:

![artikeleinstellungen](https://f.cloud.github.com/assets/1551887/2447483/095e3654-ae98-11e3-90e0-19d9db9e4e3b.png)

Ein Klick darauf führt auf eine Seite ohne jegliche Einstellungsmöglichkeiten und ist für Redakteure eher verwirrend.
Konsequenterweise müsste dieses Symbol doch auch ausgegraut sein.
Gruss, Luminanz

**Comment by aschempp** [comment]
Das hat nichts mit der Doku zu tun, aber das Problem habe ich beim Contao Core bereits gemeldet: https://github.com/contao/core/issues/6753
