### ISSUE TITLE
Markdown parser on Contao.org

### ISSUE THREAD

**Issue by ciaobello** [contao/docs-archive#15]
I wonder how i could easily include the Markdown file in a contao page. Witch Markdown parser is used:

Leo wrote the following in the readme.md of the manual:

`````` .php
// The code goes here  ```{.php}  ```
``````

GitHub can handle this syntax as well but our Markdown parser cannot handle the GitHub syntax. 

A small example would be appreciated. Everithing i tried was not showing ```{.php} correctly

**Comment by leofeyer** [comment]
Please ask questions like this in the forums. (We are using the GitHub markdown API for HTML conversion and pandoc for PDF generation).
