### ISSUE TITLE
Small typo in the "managing content" chapter

### ISSUE THREAD

**Issue by leofeyer** [contao/docs-archive#151]
Hier fehlt ein "n" beim Wort "interne":

https://contao.org/de/manual/3.0/managing-content.html#inserttags

> `{{link::*}}` Dieses Tag wird mit einem Link zu einer interne**n** Seite ersetzt (ersetzen Sie \* mit der ID oder dem Alias).

**Comment by aschempp** [comment]
Fixed in 2.11 and later
