### ISSUE TITLE
Problem with asterisks

### ISSUE THREAD

**Issue by lionel-m** [contao/docs-archive#158]
Probably a conflict with the Markdown syntax.

![capture decran 2014-05-27 a 12 44 55](https://cloud.githubusercontent.com/assets/814476/3090449/7c5a01d0-e58c-11e3-885a-cf221fef6ae4.png)

**Comment by aschempp** [comment]
I can see this only happens in the 3.1 manual and newer. Dunno if the generator is to blame, @leofeyer ?

I have however also fixed the manual, because `request_token` and `version` do not expect a parameter ;-)

**Comment by leofeyer** [comment]
If the parser were the culprit, the issue would occur in every version, not only in version 3.1, 3.2 and 3.3. Is there a difference in the markdown file between version 3.0 and 3.1?

**Comment by lionel-m** [comment]
The comparison with the file version 3.0 and 3.1.

![capture decran 2014-06-01 a 20 13 37](https://cloud.githubusercontent.com/assets/814476/3142317/88654504-e9b8-11e3-9f63-d14d73b7480e.png)
![capture decran 2014-06-01 a 20 13 28](https://cloud.githubusercontent.com/assets/814476/3142318/89d51e78-e9b8-11e3-99ba-06517ffcd7a9.png)

And new text from the line 1268 to 1435.

**Comment by leofeyer** [comment]
After a lot of debugging, I give up wanting to fix the issue in the parser. I have now simply added a `str_replace()` to correct the wrong transformations.

**Comment by lionel-m** [comment]
Thanks
