### ISSUE TITLE
Default documentation version

### ISSUE THREAD

**Issue by seaneble** [contao/docs-archive#161]
Currently, URLs like
- https://contao.org/de/insert-tags.html
- https://contao.org/de/configuring-the-live-server.html#requirements

are redirected to the Contao 3.0 documentation. In case of the requirements page, this is very misleading, because the URL is referenced on the download page and thus people downloading Contao 3.3 might get the impression, MySQL 4.1 might be sufficient for Contao.

I guess the URLs should always link to the most current documentation. On the downloads page, the requirements should be referenced separately for each version (3.x and LTS) because these requirements can differ from each other.

**Comment by leofeyer** [comment]
Fixed. However, this is not an issue of the docs parser. The old URLs (the real old ones) are being redirected via `.htaccess`, so I had to adjust the version number there.
