### ISSUE TITLE
Inserttag file für Dateilinks mit UUID

### ISSUE THREAD

**Issue by Aybee** [contao/docs-archive#162]
Hallo Andreas, habe gerade herausgefunden, dass man mit
{{file::UUID}}
z.B.
{{file::18ef1b2d-fb86-11e3-a848-001d090b5b73}}
einen Pfad zu der Datei bekommt. Das ist leider nicht dokumentiert.
https://github.com/contao/docs/blob/3.2/manual/de/04-Managing-content.md#include-elemente
Ich finde da evtl. nicht die richtigen  Worte für und weiß auch nicht, ab welcher Version das geht. Könntest du das bitte übernehmen?

**Comment by Aybee** [comment]
https://github.com/contao/core/issues/5512

**Comment by lionel-m** [comment]
@aschempp It can be closed. Thx
