### ISSUE TITLE
Hook getUserNavigation not documented

### ISSUE THREAD

**Issue by tristanlins** [contao/docs-archive#17]
The Hook `getUserNavigation` is not documented.

**Comment by aschempp** [comment]
It is in the new hook documentation: https://github.com/contao/docs/blob/3.0/hooks/hooks/getUserNavigation.md

**Comment by tristanlins** [comment]
I only saw it is not in the documentation on contao.org ...

**Comment by tristanlins** [comment]
this is already documented, see comment from @aschempp
