### ISSUE TITLE
prepareFormData hook untranslated in English

### ISSUE THREAD

**Issue by lionel-m** [contao/docs-archive#181]
Ref.: https://github.com/contao/docs/commit/7fb9ec15ba59383817b3f1598aeb89805c402b02

**Comment by aschempp** [comment]
@HumanDigital is going to add that as far as I know :-)

**Comment by HumanDigital** [comment]
First draft done … #182

**Comment by aschempp** [comment]
Added in bbae58f279bb9ed041d15ef8577b62c99780e042

**Comment by lionel-m** [comment]
:+1:
