### ISSUE TITLE
Broken link - Methode find()

### ISSUE THREAD

**Issue by lionel-m** [contao/docs-archive#184]
> Nahezu alle findBy-Methoden unterstützen als letzten Parameter ein Array mit zusätzlichen Parametern, siehe Methode find().

The link `Methode find()` is broken.

https://github.com/contao/docs/blob/3.2/cookbook/de/Models.md

**Comment by aschempp** [comment]
True, do you think it should link to the API docs?

**Comment by lionel-m** [comment]
> True, do you think it should link to the API docs?

Yes it is a good idea. This is an anchor but there is apparently no paragraph in relation with this link...

api.contao.org - The link has changed?

**Comment by aschempp** [comment]
Looks like the API documentation has been removed…
