### ISSUE TITLE
Remove folder "cookbook/en/custom-module" from 3.x branches

### ISSUE THREAD

**Issue by lionel-m** [contao/docs-archive#190]
Not compatible.

**Comment by aschempp** [comment]
@qzminski what should we do with that? https://github.com/contao/docs/blob/3.4/cookbook/en/custom-module/part1.md
Could we merge it into one file only?

**Comment by qzminski** [comment]
Do what you want. I do not plan to update that tutorial.

**Comment by aschempp** [comment]
@lionel-m I think it will be compatible with GitBook, so I suggest to keep it? Or do you think it should be removed because the information is incorrect?

**Comment by lionel-m** [comment]
I propose to remove this tutorial from version 3.0 and higher. It is necessary to keep it for the version 2.11 only.

**Comment by lionel-m** [comment]
Kamil wrote an updated version in his blog. We could add a chapter "external resources".

```
    Cron jobs in Contao (Poor-Man-Cron)
        Execute cron jobs on the server
        Workflow of a cron job
        Testing cron jobs
    Using content elements in your own extension
        Fetching the content elements in your front end module

    External resources:
    * http://blog.qzminski.com/
```

@qzminski If you agree of course

**Comment by aschempp** [comment]
Good point about the external resources, but that would then be part of the new documentation website.

**Comment by aschempp** [comment]
I have now added it to the cookbook: https://docs.contao.org/books/cookbook/en/custom-module/part1.html

I think external resources should be part of the website and not a book, but lets start a new ticket for that.
