### ISSUE TITLE
Add the "getCountries" hook

### ISSUE THREAD

**Issue by lionel-m** [contao/docs-archive#192]
Chapter 7
From Contao 2.11
Reference: https://github.com/contao/core/commit/fda11832100659440d979eff992e568a13cac842

**Comment by aschempp** [comment]
see https://github.com/contao/docs/blob/3.4/api/hooks/getCountries.md

**Comment by lionel-m** [comment]
@aschempp : I did not see that there was these information. This is a good news. But we should not close these tickets because we have to complete the Contao hooks chapter in three languages before.

**Comment by aschempp** [comment]
The developer documentation should only be in english in my opinion…
