### ISSUE TITLE
Contao Documentation on GitHub Pages?

### ISSUE THREAD

**Issue by xchs** [contao/docs-archive#2]
Just an idea: would it make sense to implement the `contao/docs` repository as a [GitHub Page](http://help.github.com/pages/)?

The web address would be (for instance): http://contao.github.com/docs/

Two examples on how this could look like:
- http://xchs.github.com/contao-docs/ (standard GitHub Pages theme)
- http://xchs.github.com/contao-docs/index2.html (Twitter Bootstrap theme for Github Pages)

**Comment by aschempp** [comment]
We might think about this in the future. The main issues I see is that we discussed to use the domain dev.contao.org but still need to keep the forwarding (/issues/xxx). I suppose GitHub pages does not allow for htaccess redirects.

Also, how can I access the existing files on your page? This does not return a parsed output.
http://xchs.github.com/contao-docs/en/hooks.md

**Comment by xchs** [comment]
> The main issues I see is that we discussed to use the domain dev.contao.org but still need to keep the forwarding (/issues/xxx).

What I have seen on the [GitHub help page](http://help.github.com/pages/) (section "Custom Domains") this can be done by creating a file `CNAME` in the root of the repository. This file contains the corresponding domain name:

```
dev.contao.org
```

> I suppose GitHub pages does not allow for htaccess redirects.

Actually, I do not know. But probably not.

> Also, how can I access the existing files on your page? This does not return a parsed output.

A Markdown parsed output of the existing files you get by simply switching to the 2.11 branch: https://github.com/xchs/contao-docs/blob/2.11/en/hooks.md

The GitHub Pages ressources are all located in the `gh-pages` branch of the respective repository. So you can simply push and fetch on this branch to update the corresponding GitHub Page (as easy as usual)

**Comment by aschempp** [comment]
Uhm, that would mean I need to parse our repository to generate pages? Then that does not make sense to me...
In case you didn't know, I'm working on a Contao extension that will fetch these manuals and publish them inside Contao.

**Comment by xchs** [comment]
> In case you didn't know, I'm working on a Contao extension that will fetch these manuals and publish them inside Contao.

Ah, I didn't know that.

Anyway, it was just a thought of mine.
