### ISSUE TITLE
Extensions > Add extension

### ISSUE THREAD

**Issue by lionel-m** [contao/docs-archive#20]
There are some differences between the current version of the repository and the documentation.

Reference : https://contao.org/en/manual/3.0/extension-repository.html#adding-an-extension

It would be nice to add : 
- GitHub URL
- The new categories

**Comment by leofeyer** [comment]
Please feel free to edit the files and create a pull request. The Contao documentation is collaborative work :)

**Comment by lionel-m** [comment]
Ok
