### ISSUE TITLE
Syntax highlighting does not work with the HTML language "{.html}".

### ISSUE THREAD

**Issue by lionel-m** [contao/docs-archive#209]
See examples [in this section](https://contao.org/en/manual/3.4/managing-content.html#template-inheritance).

**Comment by aschempp** [comment]
This is a server/parser config of @leofeyer, but I'm not sure if it's worth to fix that (regarding #174)

**Comment by leofeyer** [comment]
@aschempp When are you planning the relaunch?

**Comment by aschempp** [comment]
I guess it should be together with contao.org…

**Comment by leofeyer** [comment]
So May 2015. Is this realistic?

**Comment by aschempp** [comment]
Yes, its not that much work actually. We're not gonna rewrite the manual until then…

**Comment by leofeyer** [comment]
Ok, then I don't think we should invest time to fix the parser.

**Comment by aschempp** [comment]
I think so too. Let's keep the issue open though to check on the new system.

**Comment by aschempp** [comment]
Works fine with GitBook :-)
https://docs.contao.org/books/manual/3.4/de/04-inhalte-verwalten/templates.html
