### ISSUE TITLE
Chapter 4 : The links in the table are not converted.

### ISSUE THREAD

**Issue by lionel-m** [contao/docs-archive#22]
https://contao.org/en/manual/3.0/managing-content.html#content-elements

> Markdown formatting syntax is not processed within block-level HTML tags.
> (http://daringfireball.net/projects/markdown/syntax)

**Comment by lionel-m** [comment]
There is a solution but I would like to know if it also works on contao.org ?

```
| 1 | 2 | 3 |
|:-----------|:------------|:-------------|
| test       |        [TinyMCE][2] |     test     
| test     |      test |    test    
| test       |        test |     test     
[2]: http://tinymce.moxiecode.com
```

Result :

| 1 | 2 | 3 |
| :-- | :-- | :-- |
| test | [TinyMCE](http://tinymce.moxiecode.com) | test |
| test | test | test |
| test | test | test |

**Comment by leofeyer** [comment]
No. Just use "real" HTML markup to generate tables :)

**Comment by lionel-m** [comment]
Ok but in this case we delete the links in the table ?

**Comment by aschempp** [comment]
Why not just create real links using HTML?

**Comment by leofeyer** [comment]
Not if they are made of "real" HTML tags, too. The rule is: if you start writing HTML, no markdown whatsoever will be parsed inside the block. Instead, you have to make everything HTML, also `<a>` or `<code>` tags.

**Comment by lionel-m** [comment]
Ok thx.
