### ISSUE TITLE
rgxp digit

### ISSUE THREAD

**Issue by Aybee** [contao/docs-archive#222]
https://github.com/contao/docs/blob/3.4/manual/de/06-Data-Container-Arrays.md
Dort steht

> digit Erlaubt nur numerische Zeichen (inklusive Punkt [.] und Minus ­).

In der Hilfe zum Feld im Formulargenerator steht

>   Erlaubt numerische Zeichen, Minus (-), Punkt (.) und Leerzeichen ( ).

Ich weiß jetzt nicht, welches davon richtig ist.

**Comment by aschempp** [comment]
Wenn du es ausprobierst und berichtest, können wir die Doku ggf. anpassen ;-)

**Comment by Aybee** [comment]
Ok, hab's getestet. Leerzeichen sind nicht möglich. Muss ich da jetzt noch ein Ticket im core erstellen?

**Comment by aschempp** [comment]
Falls der Satz im englischen falsch ist, ja. Die deutsche Übersetzung erfolgt ja auf Transifex und nicht im Core. Danke für die Prüfung!

**Comment by Aybee** [comment]
https://github.com/contao/core/issues/7695
