### ISSUE TITLE
Add version warning to french manual

### ISSUE THREAD

**Issue by aschempp** [contao/docs-archive#223]
Please add the version warning about the outdated version. The english version looks like this:

```
> **Caution** You are reading the documentation for Contao 3.3 which 
> is not maintained anymore. Consider upgrading your installation!
```

The `**Caution**` part needs to remain in english as this is a formatter (see https://github.com/erixtekila/gitbook-plugin-richquotes#gitbook-plugin--transform-annotated-quotes-to-notes).
It should only be added to the manual for version 3.3!

**Comment by lionel-m** [comment]
Hi,
- What do you think of changing the term "manual" with "documentation" in order to standardize.
- Do we translate the license or it stays in English? I think it would be better to translate.

> **Manual** for Contao 3.3
> This is the official **manual** for users and developers ...
>  ... You are reading the **documentation** for Contao 3.3 which 

Thanks

**Comment by lionel-m** [comment]
The documentation includes the cookbook, manual, etc. I mixed up these two terms...

It remains the translation of the license or not.

**Comment by aschempp** [comment]
I did not translate the license, not sure if there are translated versions available, i wouldnt want to translate that myself

**Comment by lionel-m** [comment]
I think just this part because it is not translated into German. Not Creative Commons part.

> The Contao manual is licensed under a [Creative Commons Attribution 3.0
> License][2] license (CC BY-NC-SA 3.0). If you want to redistribute a modified or
> unmodified version of the manual, you can do so under the license terms.
> 
> If you contribute to the manual, e.g. by creating pull requests, you grant us
> full usage rights of any content you create or upload. You also ensure that your
> content does not violate any third-party rights.
> 
> We are not claiming exclusive usage rights, therefore you are free to use your
> contributed content (e.g. texts or images) in any other project as well.
