### ISSUE TITLE
Inserttags link::back

### ISSUE THREAD

**Issue by Aybee** [contao/docs-archive#227]
https://github.com/contao/docs/blob/49398e98493e7a811ee98a75fd651d62e54104b4/manual/de/04-Managing-content.md#user-content-link-elemente
Kann man zu link::back ein Beispiel dazu machen? Ich wüsste nicht, wie ich link::back in Verbindung mit link_open:: benutzen sollte. Vielleicht so?
`{{link_open::{{link::back}}}}{{link_close}}`

Auch der Text sollte evtl. geändert werden, da `{{link_back}}` den kompletten A-Tag generiert.

``` html
<a title="Go back" href="javascript:history.go(-1)">Go back</a>
```

Momentan steht da

> Dieses Tag wird mit der zuletzt besuchte Seite ersetzt.

**Comment by lionel-m** [comment]
`{{link_open::}}{{link::back}}{{link_close}}` :

``` HTML
<a title="Go back" href="javascript:history.go(-1)">Go back</a>
```

But in this case this is equivalent to writing `{{link::back}}`. We can not change "Go back" using `{{link_open::}}` anyway.

[{{link::back}}](https://github.com/contao/core/blob/8f678aaf08102432f943241a90d13c1c308741bd/system/modules/core/library/Contao/Controller.php#L909) 
[{{link_open::}}](https://github.com/contao/core/blob/8f678aaf08102432f943241a90d13c1c308741bd/system/modules/core/library/Contao/Controller.php#L1017)

**Comment by Aybee** [comment]
Your code 

> `{{link_open::}}{{link::back}}{{link_close}}`

Is not the same as mine. Watch the nested part. But anyway. I'm only wondering how this help text is ment.

> Can also be used with "link_open", "link_url" and "link_title".

How can we mix this insert tags together?

**Comment by lionel-m** [comment]
I know but your code does not work. You have to write it like in my example.

**Comment by Aybee** [comment]
But I can't see an advantage when using this construct.

**Comment by lionel-m** [comment]
I found how to write the different variants...

`{{link_url::back}}`  return:
`javascript:history.go(-1)`

`{{link_open::back}}Personalized text{{link_close}}` return:
`<a title="Go back" href="javascript:history.go(-1)">Personalized text</a>`

`{{link_title::back}}` return:
`Go back`

Unfortunately, the second does not change the title attribute. logically it should be:
`<a title="Personalized text" href="javascript:history.go(-1)">Personalized text</a>`

**Comment by Aybee** [comment]
Then I think we should slightly change the text to "The word 'back' can also be used with "link_open", "link_url" and "link_title" instead an ID."

**Comment by lionel-m** [comment]
Yes with examples perhaps... I'll make a PR.

**Comment by Aybee** [comment]
Yes, with examples. Thank you.

related https://github.com/contao/core/issues/7732

**Comment by aschempp** [comment]
see #239
