### ISSUE TITLE
Broken link - Module::compile

### ISSUE THREAD

**Issue by lionel-m** [contao/docs-archive#230]
See the link : [Module::compile – Compile the current element](https://github.com/contao/docs/blob/3.3/api/classes/Module/generate.md#see-also)

**Comment by aschempp** [comment]
Not sure what you mean? The API-Docs are not used yet.

**Comment by lionel-m** [comment]
I just found a broken link [on this page](https://github.com/contao/docs/blob/3.3/api/classes/Module/generate.md#see-also).
