### ISSUE TITLE
Split manual into chapters

### ISSUE THREAD

**Issue by aschempp** [contao/docs-archive#233]
With gitbook it is now possible to split the manual into "unlimited" number of chapters. I think for the beginning, two levels should be sufficient, so we need to
1. For every current document, create a folder with the name. I would use the `h1` of each document (so localized now) and add the leading number for sorting.
2. Move each document into it's folder and rename it to README.md
3. For every `h2`-headline in the README of each folder, create a new file with the name of the section and move everything of that `h2` to the new document.
4. Update the `SECTIONS.md` accordingly (see http://help.gitbook.com/format/chapters.html)

Be aware that we should do this only for the manual (and not for cookbooks)! And first, **only for version 3.2**. I will then see how we merge that into 3.4.

Let me know if anything is unclear :-)

**Comment by lionel-m** [comment]
Hi,

At the moment we have this URL: `***/***/manual/3.x/en/01-Installation.html`

I would like to propose:
- `***/***/manual/3.x/en/installation.html` (h1)
  - `***/***/manual/3.x/en/installation/installing-contao.html` (h2)
  - `***/***/manual/3.x/en/installation/using-the-safe-mode-hack.html` (h2)

Or with a number for each chapter
- `***/***/manual/3.x/en/01/installation.html` (h1)
  - `***/***/manual/3.x/en/01/installing-contao.html` (h2)
  - `***/***/manual/3.x/en/01/using-the-safe-mode-hack.html` (h2)

Personally I prefer the first. What do you think?

**Comment by lionel-m** [comment]
[Here the result with the summary file](https://github.com/lionel-m/docs/commit/03ba3a1c7370bc9acdfcebed21a41858fe3be14e) and the number for the chapters.

**Comment by aschempp** [comment]
I would call the folder `en/01-installation/…`. And the index file must be called `README.md`. So instead of `/en/01/installation.md` it should be `/en/01-installation/README.md`

**Comment by lionel-m** [comment]
I modified the summary according to your last comment. Is it ok like that?
https://github.com/lionel-m/docs/commit/883f387a8c02e12d157c3a06a6fa82adfe54b21c

**Comment by aschempp** [comment]
Yes that looks perfect, what do you think?

**Comment by lionel-m** [comment]
Yes perfect with the number and the name.

**Comment by lionel-m** [comment]
Here the new structure in French : https://github.com/lionel-m/docs/tree/subchapters/manual/fr

I need to change the URL of each image. Do we keep a global folder "images" for all images or do we create an "images" folder in each chapter folder?

**Comment by aschempp** [comment]
Technically it does not matter. I think it would be cleaner to move the images to the subfolder. I guess then you also do not need to change the content, right?

**Comment by lionel-m** [comment]
> I guess then you also do not need to change the content, right?

Yes it's not needed. I will move the images into each sub-folder. Thx

**Comment by lionel-m** [comment]
I finished the conversion into subchapters. But this will not be possible to change the version 3.4 according to the PR of 3.2... Because the files are new, there is not history. I think this conversion must be done manually for the version 3.4 too. What do you think?

**Comment by aschempp** [comment]
Its the job of GIT to do that, and to be able to do. We'll see if it works, please create a PR for 3.2 with your changes.

**Comment by lionel-m** [comment]
> We'll see if it works

It would be great!

I need to change the internal links because the file names have changed and I create the PR.

**Comment by lionel-m** [comment]
PR created #234

**Comment by aschempp** [comment]
Closing this in favor of #234
