### ISSUE TITLE
Link without reference

### ISSUE THREAD

**Issue by lionel-m** [contao/docs-archive#235]
In the `manual/contributing.md` file, there is not a reference for this link `[GitHub flavored syntax][2]`.

**Comment by lionel-m** [comment]
Version 3.2

**Comment by aschempp** [comment]
The correct link would be http://github.github.com/github-flavored-markdown/

**Comment by lionel-m** [comment]
Thanks. The PR #236 solve this problem too.

**Comment by aschempp** [comment]
Thanks!
