### ISSUE TITLE
Update "themes" chapter in German and French

### ISSUE THREAD

**Issue by lionel-m** [contao/docs-archive#241]
This sentence was deleted in English (ref. https://github.com/contao/docs/commit/2958dc74249b3f37a6ee4ddcdca22bb004307f5f):

> Obwohl der Theme-Manager eine neue Funktion der Version 2.9 ist, handelt es sich dabei eigentlich nur um ein erweitertes Interface für etwas, das es in Contao schon immer gegeben hat.

Path : `manual/de/03-seiten-verwalten/themes.md`

I will create a PR for the French chapter

**Comment by aschempp** [comment]
Is there something to do for me here?

**Comment by lionel-m** [comment]
No, I can do it. I thought it was necessary to modify a sentence but no...
I close this ticket in favor of a PR.

**Comment by lionel-m** [comment]
See #245
