### ISSUE TITLE
Internal links with accented characters do not work.

### ISSUE THREAD

**Issue by lionel-m** [contao/docs-archive#244]
For example the link "Composants d'un thème" in `/fr/04-gestion-du-contenu/modeles.html`.

**Comment by aschempp** [comment]
Can you point me to a page in the manual? It seems to work in the table of contents?

**Comment by lionel-m** [comment]
I deleted all the accented characters in the table of contents in French or converted in German (e.g. methoden-ueberschreiben.md). So it's ok in this part of the doc.

Try for example to follow this link "Composants d'un thème" in Gestion du contenu -> Modèles.

Thanks

**Comment by aschempp** [comment]
Looks like a GitBook issue…

**Comment by lionel-m** [comment]
I will create a ticket on the GitBook repository...

**Comment by aschempp** [comment]
I dont think thats necessary, I can investigate that sometimes. Or is it very urgent?

**Comment by lionel-m** [comment]
No it is not urgent.

**Comment by aschempp** [comment]
I have added a plugin that adds automatic click-links for each headline. Please see the current 3.2 manual for example. They seem to work for me in french too, can you please try if that solves the problem?

**Comment by lionel-m** [comment]
No it does not work.
