### ISSUE TITLE
[3.2] getSearchablePages hook has wrong signature

### ISSUE THREAD

**Issue by bezin** [contao/docs-archive#250]
Hei there, 

the getSearchablePages hook has the wrong signature in the docs for version 3.2. It has two parameters ($arrPages and $intId), but that is not the case here: https://github.com/contao/core/blob/master/system/modules/core/classes/RebuildIndex.php#L74

However it is called with four parameters in https://github.com/contao/core/blob/master/system/modules/core/library/Contao/Automator.php#L399

I forked the docs and removed the $intId parameter from the signature and the description, but I am not sure about how to document the hook in Automator class?

**Comment by aschempp** [comment]
Thanks for reporting. We have started a new hook documentation a while ago and can now finally start to use it (thanks to the new https://docs.contao.org). Do you think it works like this?
https://github.com/contao/docs/blob/master/api/hooks/getSearchablePages.md

**Comment by bezin** [comment]
Thanks the link. I wasn't aware of the new Contao docs, but they look great. Thanks for the work. I think it works way better like this :)
