### ISSUE TITLE
Optimize the website for viewing on mobile devices

### ISSUE THREAD

**Issue by xchs** [contao/docs-archive#252]
When reading the manual on a mobile device in portrait mode, it could well be that the sharing icons on the right side wrap to the next line which might lead to the following rendering:

![screenshot_2015-05-08-11-00-17](https://cloud.githubusercontent.com/assets/1218766/7544873/89b187c6-f5d1-11e4-812a-a4b9c1534c1d.png)

whereas in landscape mode it looks just fine:

![screenshot_2015-05-08-11-00-46](https://cloud.githubusercontent.com/assets/1218766/7544871/8633bcea-f5d1-11e4-83db-31133e6a6243.png)

**Comment by aschempp** [comment]
see https://github.com/rtCamp/gitbook-plugin-edit-link/pull/6

**Comment by aschempp** [comment]
Fixed with the latest version of the plugin.

**Comment by xchs** [comment]
Thanks a lot.
