### ISSUE TITLE
Language selection headline

### ISSUE THREAD

**Issue by xchs** [contao/docs-archive#253]
After choosing a particular manual you will be prompted to select the preferred language:

![screenshot_2015-05-08-11-02-12](https://cloud.githubusercontent.com/assets/1218766/7544565/789c462c-f5ce-11e4-81f0-cdf71c661b0b.png)

Shouldn't we write the headline in English, too? Something like "Please select a language" for instance.

**Comment by aschempp** [comment]
That appears to be a problem in GitBook, only since we added the french version…

**Comment by aschempp** [comment]
Has been fixed meanwhile (probably due to my pull request at https://github.com/GitbookIO/gitbook/pull/757)
