### ISSUE TITLE
Add a link for the headline and manual icon

### ISSUE THREAD

**Issue by xchs** [contao/docs-archive#254]
Would you mind linking the headline as well as the icon to the corresponding manual?

![screenshot-docs contao org 2015-05-08 21-28-46](https://cloud.githubusercontent.com/assets/1218766/7544194/4c6f1a50-f5cb-11e4-8cb9-b988de328d60.png)

I always click on the manual icon and nothing happens :)

**Comment by aschempp** [comment]
I've added a link on the whole content :-)

**Comment by xchs** [comment]
It's better still. Thank you.
