### ISSUE TITLE
PDF - Table of contents

### ISSUE THREAD

**Issue by lionel-m** [contao/docs-archive#255]
The table of contents is displayed twice. The document should begin on page 3.

**Comment by aschempp** [comment]
This is because it is automatically added to the PDF. I think the only solution to remove it would be not having it in the intro, but then it would probably also be gone on the website (I can try a trick though). What do you think?

**Comment by lionel-m** [comment]
I perhaps find the solution with #262

**Comment by lionel-m** [comment]
@aschempp It does not work...

**Comment by lionel-m** [comment]
@aschempp I propose to remove the TOC in the "Introduction" chapter. The online menu can accomplish this task and the TOC will be generated in the PDF. It solves this issue...

**Comment by aschempp** [comment]
I agree, I thought about this too recently
