### ISSUE TITLE
Suggestion: document file containing the hook as well

### ISSUE THREAD

**Issue by bezin** [contao/docs-archive#279]
Hei, 
I was wondering, if it would be helpful to document the file containing the hook as well. It could look something like this:

// entry
### colorizeLogEntries

The "colorizeLogEntries" hook is triggered in the label callback for tl_log entries. 
It passes an array holding the current row data and the current label and expects a
HTML string as return value. You can use it to generate custom labels for custom 
log categories, but you may also modify existing labels. It is available from 
Version 3.3.RC1.

File: system\modules\core\dca\tl_log.php

``` .php
// config.php
$GLOBALS['TL_HOOKS']['colorizeLogEntries'][] = array('MyClass', 'colorizeLogEntries');

// MyClass.php
public function colorizeLogEntries($row, $label)
{
    // Do something
}
```

// end of entry

I would not document line numbers, because they may change, but it is unlikely that the file itself will change. Of course you can always search for the hook name over all files in your contao installation and that is what I am used to as well. But documenting it may help some people and is actually not more work for us, since you have to open the file containing the hook anyways to document it. 

Any thoughts on that appreciated :)

**Comment by aschempp** [comment]
Absolutely, see the _References_ section in https://github.com/contao/docs/blob/master/api/hooks/activateAccount.md for example.

**Comment by bezin** [comment]
Ok, I will follow your example for my contributions to the new hook documentation.

**Comment by aschempp** [comment]
Btw. I have added [the richquotes plugin](https://github.com/erixtekila/gitbook-plugin-richquotes#gitbook-plugin--transform-annotated-quotes-to-notes) to our GitBook build process. I suggest using `**Tag**` to make the version information more obvious. Only for the version in the API folder though, as there is not really enough room in the manual.

**Comment by aschempp** [comment]
Also be aware that the developer documentation (including new api/hooks) is in english only. So it will make contributing missing hooks easier and not require @lionel-m to translate everything to french ;-)

**Comment by bezin** [comment]
+1 for the version tagging. Anyhow I am confused now: shall all new hook documentations go to the api docs from now on? I would transfer the two hooks I documented on the weekend to those new docs as well. And the different api docs for different contao versions will be maintained by different branches as we maintain the manual right now?

**Comment by aschempp** [comment]
well I guess that depends on when we can release such a book. There is no real structure for a book yet, so I / we need to figure out what's best. I don't think a book only for hooks makes sense. So maybe it should contain all of the API stuff.

Regarding the different branches: no. As there is a version information, I don't think we should have different versions. We should only use the master branch.

**Comment by bezin** [comment]
I wasn't suggesting a distinct hook documentationm, I totally agree with your suggestion to have an api doc with all "API stuff". What is left to release this new book? Until then, I assume we have to add recently documented hooks to both the manual(s) and the new api docs?

I also agree with the only-master-branch approach.

**Comment by aschempp** [comment]
Well adding to the manual is a lot more effort, especially because it "requires" translation. I would prefer to rather spend that time on the API docs.

What should the API book contain in your opinion? We could for example also move the whole DCA configuration from the manual over there. But I'm not sure if documenting all classes and methods is worth it.

Btw, maybe we could discuss that in the public Mumble call (18. June)? @lionel-m is obviously very welcome to join the discussion. Most things will probably be in german but we sure can switch to english for that.

**Comment by bezin** [comment]
True, I wouldn't mind adding hooks to the API docs only and spend more time on examples rather than the German translation. So +1 from me for focusing on the new api docs. 

Yes, DCA reference for instance. I think we should improve the callbacks section as well by adding some examples and not just listing them. I always have to lookup callback handling in the core to get an idea of how one can use a callback, eg. what I have to return and so on. I don't mind reading code at all, but sometimes a detailed callback documentation would have been good ;)

Anyhow: I agree on the public mumble. I'll join you :)

**Comment by aschempp** [comment]
The callbacks should certainly be styled the same as hooks. I have started an entry page at https://github.com/contao/docs/blob/master/api/callbacks.md, but there's no content yet.

#48 already contains a lot of content from @eS-IT which was never merged.

**Comment by fiedsch** [comment]
Using the Mumble call (18. June) is certainly a good idea. As far as I'm concerned: I hope I can join (I'm on vacation and do not know if I have WiFi).

I should find some time this weekend and will prepare some input for the hooks.

@bezin These are the hooks I found to be missing: https://gist.github.com/fiedsch/892dfb88ffcf1fbf9abe. Could you let me know which ones you have on your list so we don't do duplicate work.

The input from  @eS-IT could be used for the callbacks documentation. I would split that into separate files and make the structure match the hooks structure and the create a pull request.

**Comment by lionel-m** [comment]
> @lionel-m is obviously very welcome to join the discussion. Most things will probably be in german but we sure can switch to english for that.

Thanks! I also wish to participate in this Mumble call.

**Comment by aschempp** [comment]
Great!

**Comment by bezin** [comment]
@fiedsch sorry for not answering the last days. As far as I oversee things, only the getAttributesFromDca hook is already documented. Feel free to document the others :)

And I do agree on the input by @eS-IT. We should document callbacks like hooks with an index page and one subpage per callback.

**Comment by aschempp** [comment]
I also just re-discovered pull request #143 that adds a lot of drafts for existing hooks. Maybe we can re-use that for the new documentation :-)

**Comment by aschempp** [comment]
Quick reminder about the call tonight ;-)

If anyone does not know how to use Mumble, there's a tutorial in the wiki (unfortunately only in german):
http://de.contaowiki.org/Mumble_Installation

**Comment by aschempp** [comment]
The new API book is published: https://docs.contao.org/books/api/extensions/hooks/index.html
