### ISSUE TITLE
[3.5] add getPageStatusIcon hook to api documentation

### ISSUE THREAD

**Issue by bezin** [contao/docs-archive#285]

**Comment by bezin** [comment]
I documented it already, but I pushed some commits to master for another PR instead of creating a new branch. If I start a PR on this issue Github takes all the commits from master as well. Any suggestion how I may fix this?

**Comment by aschempp** [comment]
It's pretty easy, but it depends on the GIT client you're using. In SourceTree, you can simply checkout any commit, which will result in a HEAD branch. You can then create a new branch based on current HEAD.
