### ISSUE TITLE
[3.2] add storeFormData-Hook to api documentation

### ISSUE THREAD

**Issue by bezin** [contao/docs-archive#295]
Reference: https://github.com/contao/core/blob/support/3.2/system/modules/core/forms/Form.php#L445

Does somebody know, since when this hook is available?

**Comment by aschempp** [comment]
`git blame` says "added" in https://github.com/contao/core/commit/2ae714b52c7b1476755fc3b42e2c7001ff89266b which means it was there since at least Contao 3.0 …

**Comment by bezin** [comment]
Thanks! That should be close enough :D

**Comment by Toflar** [comment]
2.11 - https://github.com/contao/core/issues/3182

**Comment by bezin** [comment]
Perfect, thanks a lot. I'll add it to the documentation

**Comment by bezin** [comment]
Well, confusion at its best: the "storeFormData" hook I wanted to document is not in the 3.2 manual, but in the new hook documentation. BUt the "prepareFormData" hook, which is documented in the manual, is not in the new api docs. 

Backport or not?

**Comment by aschempp** [comment]
When I started the new hook documentation about two years ago, I didn't use the existing documentation but started mostly from scratch. That's why it's likely they are not identical.

I wouldn't bother backporting if we can get the hook documentation online within reasonable time (let's say until the camp :-)).

**Comment by bezin** [comment]
I'll close that here, because the original issue is obsolete and anything else should be discussed in the public mumble call tomorrow :)

**Comment by aschempp** [comment]
:+1:
