### ISSUE TITLE
Manual Links

### ISSUE THREAD

**Issue by cgpro** [contao/docs-archive#298]
https://contao.org/de/manual.html
... the links don't work anymore. (all versions)

https://contao.org/de/manual/3.4/data-container-arrays.html#referenz
-> Die angeforderte Seite "de/manual/3.4/data-container-arrays.html" existiert leider nicht.

**Comment by aschempp** [comment]
Unfortunately, there's nothing I can do about the old site. @leofeyer has to fix that after the holidays.

Anyways, I suggest you use the new documentation at https://docs.contao.org

**Comment by leofeyer** [comment]
The issue will resolve automatically as soon as we have relaunched the website (scheduled for next week).

**Comment by cgpro** [comment]
Don't forget to redirect the old links (SEO) ;-)

Thanks!
