### ISSUE TITLE
External resources

### ISSUE THREAD

**Issue by aschempp** [contao/docs-archive#304]
- http://contao.wiki
- http://blog.qzminski.com/article/create-a-custom-module-the-basics.html

**Comment by lionel-m** [comment]
@aschempp : Instead of creating a new section in the documentation, we could create a new repository on github in the same idea as an "[awesome list](https://github.com/sindresorhus/awesome)". We can add blog articles etc. It's quicker to maintain and people can contribute easily by creating tickets or PRs. WDYT?

**Comment by aschempp** [comment]
where do you see the difference between *a folder* and *a new repo*?

Also I wonder if we need this at all. I guess we should add the wiki to the external resources on docs.contao.org? The other link has already been copied to the cookbook, right?

**Comment by lionel-m** [comment]
I'm not just talking about the two links above... I propose to create a list of external resources in a markdown file and maintained in a new repository. Then we will create a link on docs.contao.org under "External Resources" to this repository like the "YouTube Channel".

**Comment by lionel-m** [comment]
> where do you see the difference between a folder and a new repo?

Of course we can create this list in a new folder in this repository. Then we will create a link on docs.contao.org under "External Resources" to this list like the "YouTube Channel".

> Also I wonder if we need this at all. I guess we should add the wiki to the external resources on docs.contao.org? The other link has already been copied to the cookbook, right?

I'm not just talking about the two links above but a list of useful external resources we can find on the web. We can ask on the DE/FR/EN forums to contribute.

**Comment by aschempp** [comment]
Ah, I see. But we could as well push that list to the website directly, or would you not do that? Maybe not really a new book, but something similar?

On the other hand, I wonder if that's not something we should put in the Wiki and let people curate it? And simply link from the docs website to that Wiki page?

**Comment by aschempp** [comment]
FYI I just added a link to the wiki on docs.contao.org
I don't really like it though, as there are also different links on https://contao.org/en/support.html

Maybe we should just link to that page for general support links? What do you think?

**Comment by lionel-m** [comment]
> Maybe we should just link to that page for general support links? What do you think?

Yes it's better 👍

**Comment by aschempp** [comment]
I have update the docs.contao.org page, like it like this?

**Comment by lionel-m** [comment]
Perfect like that 👍
