### ISSUE TITLE
Missing informations

### ISSUE THREAD

**Issue by lionel-m** [contao/docs-archive#31]
**Reference**
- [x] colorpicker
- [x] csv
- [x] sql (cda7513)

**Insert tags**
- [x] toggle_view (https://github.com/contao/docs/commit/f72fe2436efc9dc1814d79fd54f39f0458fdffe3)

**Hooks**
- [ ] getCountries() (see issue #192)
- [ ] getCombinedFile() (see issue #193)

**Comment by lionel-m** [comment]
[#5132](https://github.com/contao/core/issues/5132)

**Comment by aschempp** [comment]
CSV added in #144
