### ISSUE TITLE
I dont know if I'm right here .. On https://docs.contao.org/en/  Cover for 3.5 still marked as beta.

### ISSUE THREAD

**Issue by ciaobello** [contao/docs-archive#317]
Probably would be a good idea to remove the "beta" mark from the Conto 3.5 book cover and add the outdated on 3.2.

**Comment by aschempp** [comment]
True. But as soon as we do that, the manuals for Contao 3.2 and 3.4 will go unmaintained. Not sure if that's too early?

/cc @lionel-m @bezin @fiedsch

**Comment by ciaobello** [comment]
Probably it just needs a new tag for 3.2: "transmission" and some explanations what the tags mean.

**Comment by fiedsch** [comment]
I don't know how the labels are generated, and thus how much work it would be to change or extend them, but how about labels like "current LTS" that describe the status of the release?

**Comment by aschempp** [comment]
The labels are created by me. They are limited due to the available width, and obviously there can only be one. It does not make sense to mark Contao 3.5 as LTS in my opinion if it's the only supported version (except if there would be a Contao 4 manual).

**Comment by lionel-m** [comment]
I propose to separate them into two groups. Is the ribbon necessary?

![capture d ecran 2015-08-02 a 20 22 30](https://cloud.githubusercontent.com/assets/814476/9027389/3a80f652-3954-11e5-8847-d165409fcf9e.png)

**Comment by aschempp** [comment]
I have now marked 3.5 as "current" and all others as beta. I liked the idea of @lionel-m but it does not really make sense if they are all outdated. Also be aware of the mobile version where the items will be a horizontal slider (and two headlines would mean two sliders).

**Comment by ciaobello** [comment]
+1
