### ISSUE TITLE
[3.5] System requirements are incorrect.

### ISSUE THREAD

**Issue by discordier** [contao/docs-archive#318]
The system requirements are noted to be the same as for Contao 3.4 however this is definately not true. :)

See https://community.contao.org/de/showthread.php?58418-Migration-fehlgeschlagen&p=378851&viewfull=1#post378851

**Comment by aschempp** [comment]
Meanwhile fixed: https://docs.contao.org/books/manual/3.5/en/01-installation/configuring-the-live-server.html
