### ISSUE TITLE
It's hard to detect links in text with theme Sepia

### ISSUE THREAD

**Issue by Aybee** [contao/docs-archive#335]
Ist mir gerade hier aufgefallen https://docs.contao.org/books/manual/3.5/de/01-installation/contao-installieren.html dass man (ich) die Links so gut wie gar nicht im Text erkennen kann.

"über das Extension Repository" ist eigentlich gar nicht zu erkennen und "Contao Official Demo" ist nur italic.

Kann man da noch was mit CSS machen um die irgendwie hervorzuheben? Ich denke ein einfaches `text-decoration:underline` wäre super und ausreichend.

**Comment by fiedsch** [comment]
Aus meiner Sicht sind die Links "blau genug" -- auch, wenn sie nicht gerade ins Auge springen. Vielleicht wäre eine weiter Option (neben "Hell", "Sepia" und "Nacht" z.B. "Hoher Kontrast") eine Option.

**Comment by aschempp** [comment]
Das Design kommt (bisher) nicht von uns sondern direkt von @gitbook. Falls jemand ein eigenes Theme erstellen und betreuen will können wir gerne was anpassen, aber mir fehlt definitiv die Zeit dazu.

**Comment by Aybee** [comment]
Blau? Ah ok, ich hatte gar nicht gesehen, dass man dort auch Themes auswählen kann. **Das Ticket betrifft nur das Theme Sepia.**

@aschempp Vielleicht kannst du das Theme Sepia ganz deaktivieren oder ein anderes Theme dafür nehmen, oder Sepia kopieren und mit unterstrichenen Links wieder einsetzen, falls das nicht zuviel Arbeit ist.

Falls du einen Link zu einem Ticketsystem für das Theme hast, kannst du mir den gerne geben, ich würde ein Ticket dazu machen, da ich es für einen Fehler halte.

**Comment by aschempp** [comment]
Ich hab keinen Link, aber Google findet bestimmt was ;-)

**Comment by Aybee** [comment]
Ticket erstellt https://github.com/GitbookIO/gitbook/issues/949

**Comment by aschempp** [comment]
Thanks!
