### ISSUE TITLE
Problem with the select input for versions

### ISSUE THREAD

**Issue by lionel-m** [contao/docs-archive#346]
The field always displays the version 3.5

![capture d ecran 2015-11-09 a 18 23 09](https://cloud.githubusercontent.com/assets/814476/11041076/e6f109c8-870f-11e5-8f76-b9124e59e226.png)

**Comment by aschempp** [comment]
Unfortunately, that’s a problem in the plugin, and there is no GitHub/Open Source version to easily fix and contribute. But I’ll look into it somewhen

**Comment by lionel-m** [comment]
Is this ? https://github.com/GitbookIO/plugin-versions

**Comment by aschempp** [comment]
Yes! I was too stupid to find it :D

**Comment by aschempp** [comment]
https://github.com/GitbookIO/plugin-versions/pull/1
