### ISSUE TITLE
User Manual Version 3.5 Abschnitt 5.1 Benutzer und Gruppen

### ISSUE THREAD

**Issue by Mynyx** [contao/docs-archive#353]
Im User Manual zur Version 3.5 ist auf der Seite 5.1 Benutzer und Gruppen im Abschnitt Pagemounts (https://docs.contao.org/books/manual/3.5/de/05-systemadministration/benutzer-und-gruppen.html#pagemounts) ein Link "Zugriffsrechte", der allerdings auf https://docs.contao.org/books/manual/3.5/de/03-seiten-verwalten/module.html#zugriffsschutz zeigt. 

In dem Abschnitt Pagemounts geht es um die Rechte von Benutzern, "Zugriffsrechte", im verlinkten Abschnitt geht es dagegen um die Rechte von Mitgliedern, "Zugriffsschutz".

**Comment by aschempp** [comment]
Der Link müsste wohl hierhin?
https://docs.contao.org/books/manual/3.5/de/03-seiten-verwalten/seitentypen.html#zugriffsrechte

**Comment by Mynyx** [comment]
Der Screenshot ist außerdem auch noch aus der alten Demo.

**Comment by aschempp** [comment]
Behoben in e048a36e2bb0a72d5e0bdce1c28509951be177a7
