### ISSUE TITLE
missing the domain target for the installation

### ISSUE THREAD

**Issue by Aybee** [contao/docs-archive#364]
On this page
EN - https://github.com/contao/docs/blob/4.0/manual/en/01-installation/installing-contao.md
DE - https://github.com/contao/docs/blob/4.0/manual/de/01-installation/contao-installieren.md
I'm missing the hint, that the domain has to be rooted to the Contao_ROOT/**web**/ folder and not to the Contao_ROOT/ folder.

**Comment by aschempp** [comment]
You're right about this. Any suggestions for a description or a chapter about it? Be aware that the `/web` folder is only necessary for live installations, not for `localhost` or `app_dev.php`.

**Comment by Aybee** [comment]
I don't know enough about installing C4 and its variations regarding live, localhost, app_dev.php... So its up to you to decide.

I've had many troubles after installing C4 live on apache. No symlink for /files, no chance to delete or even see symlinks with FileZila. I only was able to completely delete my installation with SSH on command line.

**Comment by lionel-m** [comment]
Resolved in #438
