### ISSUE TITLE
create 4.1 branch and increase PHP minimum requirement

### ISSUE THREAD

**Issue by fritzmg** [contao/docs-archive#369]
As discovered in contao/standard-edition#37 the minimum requirements for Contao 4 have changed in Contao 4.1. The current manual for Contao 4.0 lists PHP **5.4.0** as the minimum requirement » https://github.com/contao/docs/blob/4.0/manual/en/01-installation/configuring-the-live-server.md. 

However, in Contao 4.1 that has changed to PHP **5.5.0**. This should probably be reflected in the documentation as well.

**Comment by aschempp** [comment]
I suggest we add a Contao 4.2 book once its released and simply skip 4.1… 4.0 will then wander into the outdated secion.

**Comment by aschempp** [comment]
The book for Contao 4.2 is now available and updated.
https://docs.contao.org/books/manual/4.2/

**Comment by fritzmg** [comment]
PHP Intl extension is still missing under https://docs.contao.org/books/manual/4.2/en/01-installation/configuring-the-live-server.html

**Comment by aschempp** [comment]
I'm not aware that Intl is a requirement? @leofeyer

**Comment by fritzmg** [comment]
Yes, see https://github.com/contao/check/issues/95

**Comment by aschempp** [comment]
Thanks for the info! Can you provide a pull request for the necessary adjustments?

**Comment by fritzmg** [comment]
Yes, will do when I have the time :). Want to add a few other things as well.

**Comment by lionel-m** [comment]
> Yes, will do when I have the time :). Want to add a few other things as well.

👍

**Comment by fritzmg** [comment]
Btw. shouldn't PHP extensions like `SOAP` be removed from the requirements, since there is no Extension Repository anymore? Also technically you do not need `Phar` I think - though you need it for composer of course.

Not sure about `mbstring` and `mcrypt`.

**Comment by aschempp** [comment]
Please create new issues or preferably pull requests, this one is for another topic and already closed.
