### ISSUE TITLE
Problem with the languages drop-down list

### ISSUE THREAD

**Issue by lionel-m** [contao/docs-archive#376]
To reproduce the problem, select the Contao 4 manual and a language. The drop-down list displays Contao 4. Then select a chapter and the drop-down list will change to display Contao 3.5 (fortunately we are not redirected to the Contao manual v3.5).

**Comment by aschempp** [comment]
That problem was fixed in the plugin (see my PR at https://github.com/GitbookIO/plugin-versions/pull/1). However, the old books like Contao 3.4 are not updated anymore and did not get the fixed version of the plugin… Are you sure the problem happened in the 4.0 manual?

**Comment by aschempp** [comment]
Also see #346 :D

**Comment by lionel-m** [comment]
> Are you sure the problem happened in the 4.0 manual?

Yes

> Also see #346 :D

Of course it is a new problem ;)

But I retested now and I have `pageTr` after clicking on a chapter... 

![capture d ecran 2016-06-27 a 17 38 35](https://cloud.githubusercontent.com/assets/814476/16385663/06f0b60e-3c8e-11e6-9c0d-f26c273be3ec.png)

**Comment by lionel-m** [comment]
And the icons for anchor links are no longer displayed.

**Comment by lionel-m** [comment]
Everything is solved after you have updated GitBook and Plugins 👍
