### ISSUE TITLE
Contao compatibility in the cookbook.

### ISSUE THREAD

**Issue by lionel-m** [contao/docs-archive#378]
Some chapters are compatible with Contao 2 and the others with Contao 3 etc. It would be nice to add a compatibility information or find an alternative solution.

We can create a cookbook for Contao 3.x and another for Contao 4.x and we specify the compatibility with the minor releases e.g. "Compatible with Contao from 3.2 to 3.5" in each chapter.

**Comment by lionel-m** [comment]
@christianromeni cc for information after discussion in https://github.com/contao/docs/pull/375#issuecomment-221751042.

**Comment by aschempp** [comment]
I would suggest to add comments like we do in hooks for the version information? https://github.com/contao/docs/blob/master/api/extensions/hooks/addLogEntry.md

**Comment by christianromeni** [comment]
To be honest... I would recommend that every version would get its own. Reason behind this, is that it might be easily overseen that this function is only working in a specific version.

Also, if I know what version I'm working with, I would always first check the version, then the functionality.
Its the same in the manual.

**Comment by aschempp** [comment]
The cookbook is usually developer related, and the changes for developers in minor releases are so small it does not really make sense to start a new cookbook.

**Comment by lionel-m** [comment]
We can close this issue for the moment (?)
