### ISSUE TITLE
Missing tl_class on reference eval

### ISSUE THREAD

**Issue by Aybee** [contao/docs-archive#379]
Missing tl_class on 
https://docs.contao.org/books/api/dca/reference.html#evaluation
https://github.com/contao/docs/edit/master/api/dca/reference.md

it is mentioned here
https://docs.contao.org/books/api/dca/palettes.html#arranging-fields
https://github.com/contao/docs/edit/master/api/dca/palettes.md

**Comment by aschempp** [comment]
see #380

**Comment by Aybee** [comment]
Thank you very much.
