### ISSUE TITLE
Insert tag page:: for all fields?

### ISSUE THREAD

**Issue by Aybee** [contao/docs-archive#389]
Hallo, habe gerade festgestellt, dass `{{page::cssClass}}` die CSS-Klasse der Seite ausgibt, obwohl dieser Insert Tag nicht dokumentiert ist.

Ist es denn so, dass damit tatsächlich jedes Feld aus tl_page ausgegeben werden kann? Wenn ja, dann könnte man das in der Doku vielleicht noch ergänzen.

Trifft das vielleicht auch noch auf andere Gruppen von Insert Tags zu? Evtl. auf `user::`?

**Comment by aschempp** [comment]
Das ist korrekt, siehe auch https://github.com/contao/docs/pull/240. Leider hatte @Teetrinker seinen Pull-Request damals nicht fertigstellen.

**Comment by Aybee** [comment]
Ah, ok. Das hier würde dann reichen:

> {{page::*}} Dieses Tag wird mit dem Inhalt eines Feldes von tl_page der aktuellen Seite ersetzt (ersetzen Sie \* mit dem Feldnamen).

**Comment by aschempp** [comment]
Ja, ich denke sowas würde reichen :-)

**Comment by lionel-m** [comment]
Resolved in #436 and #437
