### ISSUE TITLE
[4.2] remove some PHP requirements?

### ISSUE THREAD

**Issue by fritzmg** [contao/docs-archive#393]
Since the Extension Repository is not part of Contao 4 anymore, can the `SOAP` requirement be dropped from the documentation?

Also since there is no Live Update in Contao 4, the `Phar` requirement could also be dropped - however you need that to run `composer.phar` of course.

I am not sure whether `mbstring` and `mcrypt` are still in use.

**Comment by xchs** [comment]
> Also since there is no Live Update in Contao 4, the Phar requirement could also be dropped - however you need that to run composer.phar of course.

The new Contao Manager, however, would still need the `Phar` extension (see https://contao.org/de/news/informationen-zum-contao-manager.html).

**Comment by aschempp** [comment]
`mcrypt` is used by the `Encryption` class, if someone would encrypt a field. The core does not, but an extension might do that. Therefore it's still a requirements.

`mbstring` is also required for UTF-8 support.

**Comment by aschempp** [comment]
Oh, and `SOAP` certainly **can** be dropped for Contao 4 manual.

**Comment by fritzmg** [comment]
closing in favor of #392
