### ISSUE TITLE
Replaced richquotes with callouts

### ISSUE THREAD

**Issue by aschempp** [contao/docs-archive#401]
Due to upgrading to GitBook 3 I had to replace the _richquotes_ plugin with _callouts_. See 4a70a6d86cfeda0dab346334c041314aea1b590e for an example.

Can you update the french manual and add titles?

I also wonder if it would make sense to add titles depending on the situation instead of the warning type?

**Comment by lionel-m** [comment]
> I also wonder if it would make sense to add titles depending on the situation instead of the warning type?

Do you have an example?

**Comment by aschempp** [comment]
see https://docs.contao.org/books/manual/4.2/en/01-installation/installing-contao.html for the warning, info and danger boxes.

**Comment by lionel-m** [comment]
Sorry but you say for changing for example `Warning` with a more relevant title depending of the content box?

**Comment by aschempp** [comment]
For french, there is currently no "Warning" at all (or at least not a french version). We might also add customized titles, but I don't know if that is worth the effort?

**Comment by lionel-m** [comment]
> We might also add customized titles, but I don't know if that is worth the effort?

It is sometimes difficult to find a customized title... I prefer to keep the keywords.

**Comment by aschempp** [comment]
Fine with me. Then please add the french versions (check out the german manual) :-)

**Comment by lionel-m** [comment]
It's done

**Comment by aschempp** [comment]
Closed in favor of #406

**Comment by aschempp** [comment]
FYI, I have updated the styles so the headline is inline, I think it looks way better now :-)
https://docs.contao.org/books/manual/4.2/en/01-installation/installing-contao.html

**Comment by lionel-m** [comment]
> I have updated the styles so the headline is inline

Yes good idea !

**Comment by aschempp** [comment]
I actually stole it [from PayPal](https://developer.paypal.com/docs/classic/ipn/integration-guide/IPNIntro/) 😝
