### ISSUE TITLE
Update the front-end-structure.jpg image

### ISSUE THREAD

**Issue by lionel-m** [contao/docs-archive#408]
It would be better to create a new image for [front-end-structure.jpg](https://github.com/contao/docs/blob/master/manual/en/03-managing-pages/images/front-end-structure.jpg). 

I propose to replace the legends with numbers and the legends will be added in the content below the image.

Which page can we use as an example? The same picture (Music Academy)?

**Comment by aschempp** [comment]
Good idea. I think we can use the new Contao Demo, can we?

**Comment by lionel-m** [comment]
> I think we can use the new Contao Demo

I will create a specific page with the same structure as the actual image used and we keep the text as it stands. Ok for you?

**Comment by aschempp** [comment]
Absolutely!

**Comment by aschempp** [comment]
Closed in favor of #411
