### ISSUE TITLE
How to a data view in Frontend template in contao

### ISSUE THREAD

**Issue by rechardeanirban** [contao/docs-archive#435]
I just try that if i add my name in a template in backend then how i view that name in frontend, and next if i change my name in backend then its automatically change in frontend view.

**Comment by fiedsch** [comment]
I don't quite get your question. 
- you do change a template in the backend
- then you want to see the changes you made in the frontend

I see two situations that might cause "problems"
- the template you changed is not used for generating the frontend page you visit
- an old version is still available in Contao's cache (see System -> Maintenance -> Purge the page cache)

**Comment by rechardeanirban** [comment]
No You cant understand my question, just suppose i make a workflow in Backend where i give a html tag and write my name, now how i can show this name in frontend, suppose example in BackEnd i write "Hello World" then how i see it in FrontEnd page ?

**Comment by xchs** [comment]
Please refer to the [forum](https://community.contao.org/) for this kind of questions. I cannot see how this issue is related to the `contao/docs` repository.
