### ISSUE TITLE
Documentation outdated: cronjob

### ISSUE THREAD

**Issue by jc97** [contao/docs-archive#499]
**Affected version(s)**
4.x

**Description**  
Cronjobs and the execution of cronjobs is described for version 3.x only. (https://docs.contao.org/books/cookbook/de/Cronjobs-in-Contao.html)

**How to reproduce**

**Comment by leofeyer** [comment]
Our new documentation has been released meanwhile. Head over to https://github.com/contao/docs and check it out. 🎉
