### ISSUE TITLE
Chapter 7 - Customizing the system configuration

### ISSUE THREAD

**Issue by lionel-m** [contao/docs-archive#59]
> Make sure to store your changes above the INSTALL TOOL START line, otherwise they will be removed by the settings module. And never use the config.phpfile to store configuration parameters, because the file might be overridden on updates!

Is it still valid ?

**Comment by aschempp** [comment]
I think so. What would not be valid in your opinion?

**Comment by lionel-m** [comment]
It's OK... I have tested now with Contao 3.1

But this also works if the line is written after  `### INSTALL SCRIPT STOP ###` and it's not removed after an update.

``` PHP
$GLOBALS['TL_CONFIG']['displayErrors'] = false;
### INSTALL SCRIPT STOP ###

$GLOBALS['TL_CONFIG']['displayErrors'] = true;

```

**Comment by aschempp** [comment]
Well that is not a custom rule, that is a core-supported value. I'm not sure what would happen if you write

``` php
$GLOBALS['TL_CONFIG']['myTest'] = 1;
```

and then go to the backend and save...

**Comment by lionel-m** [comment]
"myTest" is not deleted...

With : 

``` PHP
$GLOBALS['TL_CONFIG']['displayErrors'] = false;
### INSTALL SCRIPT STOP ###

$GLOBALS['TL_CONFIG']['myTest'] = 1;
```

Or : 

``` PHP
$GLOBALS['TL_CONFIG']['displayErrors'] = false;
$GLOBALS['TL_CONFIG']['myTest'] = 1;
### INSTALL SCRIPT STOP ###
```

It's OK. I updated the name of the comment in 52b797735a11c3a3068da271f342c53a03059fad
