### ISSUE TITLE
eval wrap deprecated?

### ISSUE THREAD

**Issue by Aybee** [contao/docs-archive#68]
Dieses 'wrap'
https://contao.org/de/manual/3.1/data-container-arrays.html#evaluation
scheint keine Wirkung mehr zu haben, ich kann es auch in dem ganzen Core nicht finden. Kann das jemand bestätigen und wenn ja, aus der Doku 3.1 entfernen?

**Comment by Aybee** [comment]
backbone und ich haben jetzt festgestellt, das bis runter zur TL 2.6 nichts davon zu finden ist.

**Comment by Aybee** [comment]
**wrap** scheint seit TL 2.6 keine Funktion zu haben

**Comment by aschempp** [comment]
Das bezieht sich vermutlich auf das alte Backend-Theme (war allerdings bis 2.7). Ich würde das Ticket aber nicht schliessen, sollte ja entfernt werden?

**Comment by aschempp** [comment]
see #74
