### ISSUE TITLE
Add 3.2 branch

### ISSUE THREAD

**Issue by lionel-m** [contao/docs-archive#78]
- https://github.com/contao/core/commit/eef9d87ea15553126d53d3248689a455b5c57c1f
- https://github.com/contao/core/commit/3503e2e5160099900cfe3027fc388daa1f37431c
- https://github.com/contao/core/commit/58851774df8ffe626a37f23b980da66e9acadf2d
- https://github.com/contao/core/commit/ecd2328fd7c410c4eefd9eddd679ff2b9c1bd4ab
- https://github.com/contao/core/commit/c938712de3d4d6c04e18d938629fa5c9052f8acc
- https://github.com/contao/core/commit/dd3e7c6e8935f0d5c705b12dab2084817853ea00
- https://github.com/contao/core/commit/f75ed81bfc2093e11b4e74b823613bee28351dcf

**Comment by aschempp** [comment]
As soon as there is either a release or something to add only to it ;-)

**Comment by lionel-m** [comment]
I will create a pull request soon before creating the new 3.2 branch. There are some corrections...

https://github.com/lionel-m/docs/compare/typos

This branch is outdated for a few days compared to the original branch. I hope it will still work.

**Comment by aschempp** [comment]
Great work! Merged into 2.11 and up (where appropriate).
PS: please delete your branches once I merged them. As I do not use GitHub to merge, it's easier to keep track what's still open ;-)

**Comment by aschempp** [comment]
Just noticed this ticket is about 3.2. Just created a 3.2 branch (which is currently identical to 3.1).

**Comment by lionel-m** [comment]
Thanks.
