### ISSUE TITLE
Hook "prepareFormData" missing in docs

### ISSUE THREAD

**Issue by senton82** [contao/docs-archive#85]
I fell over this very usefull hook by inspecting Form.php in detail and I could successfully solve my problem with it. After a short check I found that it is missing in the docs.

**Comment by Toflar** [comment]
Can you add it then? :)

**Comment by senton82** [comment]
I am not very experienced with the system, so I have no idea where to start. Sorry.

**Comment by lionel-m** [comment]
@aschempp Added in https://github.com/contao/docs/commit/7fb9ec15ba59383817b3f1598aeb89805c402b02 and https://github.com/contao/docs/commit/bbae58f279bb9ed041d15ef8577b62c99780e042
