### ISSUE TITLE
Question about the last paragraph of Chapter 3

### ISSUE THREAD

**Issue by lionel-m** [contao/docs-archive#96]
Chapter 3 -> Access rights

> Each level can have different permissions. By default, the owner of a page is
> allowed to edit the page itself as well as its articles, whereas a member of the
> group that owns a page is only allowed to edit articles. Unprivileged users have
> no writing permissions at all.

It is not a member but a user.

`... whereas a member of the ...` -> `... whereas a user of the ...`

Correct ?

**Comment by Toflar** [comment]
Correct :)

**Comment by aschempp** [comment]
well... I think this word is not related to "frontend member", but you are "member of a group". Still I think changing it to "user" might be slightly less confusing and the sentence would still work.

**Comment by lionel-m** [comment]
Thanks for the feedback.

https://github.com/contao/docs/pull/94
